### ISSUE TITLE
Unable to make fullscreen on X11 backend

### ISSUE THREAD

**Issue by baharanchi** [sony/flutter-elinux#220] opened 2023-09-11 06:55 UTC
Hello,

I built my app for elinux-x11 and used "--fullscreen" to make it fullscreen but it's not working.

I also tried using the [window_manager](https://pub.dev/packages/window_manager) package for making it fullscreen, but it didn't work since it is implemented for Windows, Mac and Linux but not for eLinux.

P.S. I am developing for the NanoPC-T4 board and can't use the Wayland backend per issue #215

**Comment by HidenoriMatsubayashi** [comment] 2023-09-11 07:27
Closing this issue as it is a duplicate of #136. Thank you.

**Closed by HidenoriMatsubayashi** 2023-09-11 07:27 UTC
Labels: duplicate
