### ISSUE TITLE
Issue after update to flutter 3.13.0

### ISSUE THREAD

**Issue by jvieira88** [sony/flutter-elinux#205] opened 2023-08-17 18:36 UTC
Hi,

There seems to be an issue after the flutter update to 3.13.0 (#204). Just had a quick look but it seems to affect some widgets such as the DropdownButton and other buttons. I reverted back to #201 and it seems fine.

Example with #204 
![image](https://github.com/sony/flutter-elinux/assets/44979572/7286fdb6-741c-4591-88f8-699c7735dcaf)

Example with #201:
![image](https://github.com/sony/flutter-elinux/assets/44979572/35f7c0a6-be24-4765-8e7f-5e2d91c77c98)

Maybe it's not related with flutter-elinux but just thought to bring it up.

**Comment by HidenoriMatsubayashi** [comment] 2023-08-17 19:46
Sorry, what is your issue?

**Comment by HidenoriMatsubayashi** [comment] 2023-08-17 19:51
The following template source files were updated in flutter 3.13.0.

- [main.cc](https://github.com/sony/flutter-elinux/blob/main/templates/app/runner/main.cc)
- [flutter_embedder_options.h](https://github.com/sony/flutter-elinux/blob/main/templates/app/runner/flutter_embedder_options.h)

Can you check if the files you are using are up to date?

**Comment by HidenoriMatsubayashi** [comment] 2023-08-18 21:23
Can you please check if this issue happen on elinux-x11 backend too?

The root cause might be https://github.com/sony/flutter-embedded-linux/pull/376.

**Comment by jvieira88** [comment] 2023-08-21 13:06
Hi @HidenoriMatsubayashi,

Running with X11 results in the same issue. 
However, both `main.cc` and `flutter_embedder_options.h` local to the project (under `/elinux/runner/`) differ from the source files you mentioned. Is there a way of refreshing these local files without having to manually execute a run command every time  there is an update?

**Comment by HidenoriMatsubayashi** [comment] 2023-08-21 13:15
> However, both main.cc and flutter_embedder_options.h local to the project (under /elinux/runner/) differ from the source files you mentioned.

Okay. So please try https://github.com/sony/flutter-elinux/issues/205#issuecomment-1682880895.

> Is there a way of refreshing these local files without having to manually execute a run command every time there is an update?

Unfortunately, there is no way to upgrade local elinux c++ files in existing projects. Please replace your local files manually.

**Comment by HidenoriMatsubayashi** [comment] 2023-08-21 18:55
Great.

> Something to keep in mind the next time I need to update the repository :)

I'll consider automatic-migration way in flutter-elinux.

Closing. Thanks.

**Closed by HidenoriMatsubayashi** 2023-08-21 18:55 UTC
